# Rustfmt Configuration
# https://rust-lang.github.io/rustfmt/

# Stable options
edition = "2021"
max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Default"

# Imports
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
reorder_imports = true
reorder_modules = true

# Comments
normalize_comments = false
wrap_comments = false

# Other
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = false
